# Generated by Django 4.2.3 on 2023-09-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_news_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="categories",
            field=models.ManyToManyField(
                blank=True, null=True, to="news.categories"
            ),
        ),
    ]
